# Generated by Django 2.0.5 on 2018-08-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40, null=True)),
                ('title', models.CharField(max_length=40, null=True)),
                ('url', models.CharField(max_length=40, null=True)),
                ('body', models.CharField(blank=True, max_length=2000, null=True)),
                ('time_st', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='news_sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('url', models.CharField(max_length=40, null=True)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('comments', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
