# Generated by Django 2.0.5 on 2018-08-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180821_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_items',
            name='body',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
