# Generated by Django 2.0.5 on 2018-08-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180821_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='active_news_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('body', models.CharField(blank=True, max_length=5000, null=True)),
                ('time_st', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
